# WASI port Make-level configuration
#
# circuitpy_mpconfig.mk expects certain Make variables (not just C
# preprocessor defines). This file provides them.
#
# IMPORTANT: CIRCUITPY_FULL_BUILD=1 (set in mpconfigboard.h) causes
# circuitpy_mpconfig.mk to default many modules to 1. We must
# explicitly disable hardware modules here at the Make level, not
# just in mpconfigboard.h, because Make uses these variables to
# decide which source files to compile and which -D flags to emit.

# No USB endpoints
USB_NUM_ENDPOINT_PAIRS = 0

# Compression level for translated messages
CIRCUITPY_MESSAGE_COMPRESSION_LEVEL ?= 0

# No USB device support
CIRCUITPY_USB_DEVICE = 0

# Long integer implementation (must match mpconfigvariant.h)
LONGINT_IMPL = MPZ

# ---- Hardware modules: default off, worker variant overrides ----
CIRCUITPY_MICROCONTROLLER ?= 0
CIRCUITPY_DIGITALIO ?= 0
CIRCUITPY_ANALOGIO ?= 0
CIRCUITPY_PWMIO ?= 0
CIRCUITPY_NEOPIXEL_WRITE ?= 0
CIRCUITPY_BOARD ?= 0
CIRCUITPY_NVM = 0
CIRCUITPY_WATCHDOG = 0
CIRCUITPY_ANALOGBUFIO = 0
CIRCUITPY_BUSIO ?= 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOCORE = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BLEIO = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_PIXELBUF = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PWMIO = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_ONEWIREIO = 0
CIRCUITPY_RTC = 0
CIRCUITPY_STORAGE = 0
CIRCUITPY_BOARD = 0

# ---- Display: default off, worker variant enables via mpconfigvariant.mk ----
CIRCUITPY_DISPLAYIO ?= 0
CIRCUITPY_FRAMEBUFFERIO ?= 0
CIRCUITPY_TERMINALIO ?= 0
CIRCUITPY_FONTIO ?= 0
CIRCUITPY_BUSDISPLAY = 0
CIRCUITPY_FOURWIRE = 0
CIRCUITPY_EPAPERDISPLAY = 0
CIRCUITPY_I2CDISPLAYBUS = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_SHARPDISPLAY = 0
CIRCUITPY_AURORA_EPAPER = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_GIFIO = 0
CIRCUITPY_BITMAPFILTER = 0
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_LVFONTIO = 0
CIRCUITPY_TILEPALETTEMAPPER = 0
CIRCUITPY_JPEGIO = 0
CIRCUITPY_PICODVI = 0
CIRCUITPY_DOTCLOCKFRAMEBUFFER = 0

# ---- Other features: disabled ----
CIRCUITPY_AESIO = 0
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_SUPERVISOR = 0
CIRCUITPY_STATUS_BAR = 0
CIRCUITPY_SETTINGS_TOML = 0
CIRCUITPY_SAFEMODE_PY = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_PIXELMAP = 0
CIRCUITPY_MSGPACK = 0
CIRCUITPY_ULAB = 0
