// qstrs specific to this port
// *FORMAT-OFF*
Q(/lib)
Q(asyncio.core)
Q(pystack_space_exhausted)
Q(__del__)
Q(errno)
Q(uctypes)
Q(__repl_print__)
Q(OrderedDict)
Q(base)
Q(function)
Q(hash)
Q(__class__)
Q(__hash__)
Q(__import__)
// Viper type annotation qstrings (needed when MICROPY_EMIT_WASM is enabled)
Q(uint)
Q(ptr)
Q(ptr8)
Q(ptr16)
Q(ptr32)
// Binary protocol API (modblinka.c)
Q(send_bin)
Q(BP_GPIO)
Q(BP_ANALOG)
Q(BP_PWM)
Q(BP_NEOPIXEL)
Q(BP_I2C)
Q(BP_SPI)
Q(BP_DISPLAY)
Q(BP_SLEEP)
Q(BP_INIT)
Q(BP_WRITE)
Q(BP_READ)
Q(BP_DEINIT)
Q(read_sensor_response)
