#!/usr/bin/env python3
"""
Generate header file with clean version info for WebAssembly port.
This removes the git hash and dirty flags from the banner.
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'py'))

from makeversionhdr import make_version_header, version
import datetime

def make_clean_version_header(repo_path, filename):
    # Get version info using git (required)
    info = version.get_version_info_from_git(repo_path)
    if info is None:
        raise SystemExit("Cannot determine version.")
    git_tag, git_hash, ver = info
    if len(ver) < 3:
        raise SystemExit("Cannot determine version.")
    else:
        version_string = ".".join(ver)
    
    # Clean up git_tag - remove git hash and dirty flag
    clean_git_tag = git_tag
    if '-g' in clean_git_tag:
        # Remove everything from -g onwards (git hash and dirty flag)
        clean_git_tag = clean_git_tag.split('-g')[0]
    
    build_date = datetime.date.today()
    if "SOURCE_DATE_EPOCH" in os.environ:
        build_date = datetime.datetime.fromtimestamp(
            int(os.environ["SOURCE_DATE_EPOCH"]), datetime.timezone.utc
        ).date()

    # Generate the file with clean version info
    file_data = f'''\
// This file was generated by ports/webassembly/makeversionhdr_clean.py
#define MICROPY_GIT_TAG "{clean_git_tag}"
#define MICROPY_GIT_HASH "{git_hash.split('-')[0]}"
#define MICROPY_BUILD_DATE "{build_date.strftime("%Y-%m-%d")}"
#define MICROPY_VERSION_MAJOR ({ver[0].replace("v", "")})
#define MICROPY_VERSION_MINOR ({ver[1]})
#define MICROPY_VERSION_MICRO ({ver[2]})
#define MICROPY_VERSION_PRERELEASE 0
#define MICROPY_VERSION_STRING "{version_string}"
// Combined version as a 32-bit number for convenience
#define MICROPY_VERSION (MICROPY_VERSION_MAJOR << 16 | MICROPY_VERSION_MINOR << 8 | MICROPY_VERSION_MICRO)
#define MICROPY_FULL_VERSION_INFO "Adafruit CircuitPython " MICROPY_GIT_TAG " on " MICROPY_BANNER_MACHINE
'''

    # Check if the file contents changed from last time
    write_file = True
    if os.path.isfile(filename):
        with open(filename, "r") as f:
            existing_data = f.read()
        if existing_data == file_data:
            write_file = False

    # Only write the file if we need to
    if write_file:
        print("GEN %s" % filename)
        with open(filename, "w") as f:
            f.write(file_data)

if __name__ == "__main__":
    repo_path = os.path.join(os.path.dirname(__file__), "..", "..")
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    else:
        filename = "build-standard/genhdr/mpversion.h"
    
    make_clean_version_header(repo_path, filename)