// This file is part of the CircuitPython project: https://circuitpython.org
//
// SPDX-FileCopyrightText: Copyright (c) 2013, 2014 Damien P. George
// SPDX-FileCopyrightText: Based on ports/unix/qstrdefsport.h
// SPDX-FileCopyrightText: Adapted by CircuitPython WASM Port Devs
//
// SPDX-License-Identifier: MIT

// Port-specific qstr definitions.
// Currently empty — qstrings are auto-generated by the build system.
// Add port-specific qstrings here if needed (e.g., for module names
// or error messages that the auto-generator doesn't discover).

// *FORMAT-OFF*
