# Worker variant: the board — display, hardware, REPL, code.py
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_FRAMEBUFFERIO = 1
CIRCUITPY_TERMINALIO = 1
CIRCUITPY_FONTIO = 1

# Hardware peripherals — C common-hal
CIRCUITPY_MICROCONTROLLER = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_PWMIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_BOARD = 1
CIRCUITPY_BUSIO = 1

# VM yield — cooperative stepping for code.py execution
MICROPY_VM_YIELD_ENABLED = 1

FROZEN_MANIFEST ?= $(VARIANT_DIR)/manifest.py
