# Worker variant: enable C display pipeline + hardware peripherals
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_FRAMEBUFFERIO = 1
CIRCUITPY_TERMINALIO = 1
CIRCUITPY_FONTIO = 1

# Hardware peripherals — C common-hal backed by OPFS endpoints
CIRCUITPY_MICROCONTROLLER = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_PWMIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_BOARD = 1
CIRCUITPY_BUSIO = 1
